name: Extension

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - "src/extension/**"
      - ".github/workflows/extension.yml"
  pull_request:
    branches:
      # Only trigger for PRs against `main` branch.
      - main
    paths:
      - "src/extension/**"
      - ".github/workflows/extension.yml"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build
      run: npm run build:prod
      working-directory: '${{ github.workspace }}/src/extension'

    - name: Install tfx-cli
      run: npm install -g tfx-cli@0.9.2

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["${{ github.workspace }}/src/extension/overrides*.json"]'

    - name: Update extension version.Minor
      uses: jossef/action-set-json-field@v2
      with:
        file: 'src/extension/task/task.json'
        field: 'version.Minor'
        value: ${{ steps.gitversion.outputs.minor }}

    - name: Update extension version.Patch
      uses: jossef/action-set-json-field@v2
      with:
        file: 'src/extension/task/task.json'
        field: 'version.Patch'
        value: ${{ github.run_number }}

    - name: Create Extension (dev)
      run: >
        tfx extension create
        --root src/extension
        --manifest-globs vss-extension.json
        --output-path $GITHUB_WORKSPACE/drop/dev
        --json5
        --overrides-file $GITHUB_WORKSPACE/src/extension/overrides.dev.json

    - name: Create Extension (prod)
      run: >
        tfx extension create
        --root src/extension
        --manifest-globs vss-extension.json
        --output-path $GITHUB_WORKSPACE/drop/prod
        --json5
        --overrides-file $GITHUB_WORKSPACE/src/extension/overrides.prod.json

    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/drop/*
        name: drop

  Publish:
    runs-on: ubuntu-latest
    needs: [ Build ]

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: drop

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install tfx-cli
      run: npm install -g tfx-cli@0.9.2

    - name: Publish to marketplace (dev)
      run: >
        tfx extension publish
        --vsix $GITHUB_WORKSPACE/dev/*.vsix
        --auth-type pat
        --token ${{ secrets.AZURE_DEVOPS_EXTENSION_TOKEN }}

    - name: Publish to marketplace (prod)
      if: startsWith(github.ref, 'refs/tags/')
      run: >
        tfx extension publish
        --vsix $GITHUB_WORKSPACE/prod/*.vsix
        --auth-type pat
        --token ${{ secrets.AZURE_DEVOPS_EXTENSION_TOKEN }}
